<a href="https://colab.research.google.com/github/Patchaa119/BSC_DPDM2025/blob/main/Midterm663020583_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Data

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# **ข้อ1** อ่านไฟล์ทั้งหมด แสดงโครงสร้างข้อมูล และอธิบายความหมายของแต่ละคอลัมน์

In [3]:
import os
path = '/content/drive/MyDrive/BSC_DPDM_Midterm2025/'
os.listdir(path)

['Input - (Operation Daily rain from API_ 2025)',
 'Daily rain - (Statistics 2012-2024)',
 'Output - (Clean monthly rain - 2025)']

## โฟลเดอร์ Input

In [4]:
input_path = path + 'Input - (Operation Daily rain from API_ 2025)/'
os.listdir(input_path)

['Stations in the model_HII.csv',
 '2025-08',
 '2025-09',
 '2025-10',
 '2025-07',
 '2025-11',
 '2025-12']

In [5]:
files = [f for f in os.listdir(input_path) if f.endswith('.csv')]
files

['Stations in the model_HII.csv']

In [6]:
station_df = pd.read_csv('/content/drive/MyDrive/BSC_DPDM_Midterm2025/Input - (Operation Daily rain from API_ 2025)/Stations in the model_HII.csv')
station_df

       Node        Lat        Long
0      ACRU  15.788054  104.642235
1      BBHN   9.536913   98.579490
2      BBUA  17.372976  103.984436
3      BCNG  17.386840  103.290870
4      BDAR  14.587073  102.495190
..      ...        ...         ...
380  YOM003  18.265924  100.177060
381  YOM008  16.708166  100.171780
382  YOM009  16.310750  100.271750
383  YOM010  18.133717  100.124596
384  YOM012  17.021260   99.819710

[385 rows x 3 columns]

### dataframe

In [7]:
monthly_folders = [
    f for f in os.listdir(input_path)
    if os.path.isdir(os.path.join(input_path, f))
]

monthly_folders.sort()
monthly_folders

['2025-07', '2025-08', '2025-09', '2025-10', '2025-11', '2025-12']

In [8]:
import re

pattern = re.compile(r'^HII_daily_rainfall_\d{4}-\d{2}-\d{2}\.csv$')

In [13]:
import os
import re
import pandas as pd

daily_input_data = []

pattern = re.compile(r'^HII_daily_rainfall_\d{4}-\d{2}-\d{2}\.csv$')

monthly_folders = [
    f for f in os.listdir(input_path)
    if os.path.isdir(os.path.join(input_path, f))
]
monthly_folders.sort()

for month in monthly_folders:
    month_path = os.path.join(input_path, month)

    files = [
        f for f in os.listdir(month_path)
        if pattern.match(f)
    ]

    print(month, 'valid daily files:', len(files))  # sanity check

    for f in files:
        file_path = os.path.join(month_path, f)
        try:
            df = pd.read_csv(file_path)

            df['Source_Month'] = month
            df['Source_File'] = f

            daily_input_data.append(df)
        except pd.errors.EmptyDataError:
            print(f"Skipping empty file: {file_path}")
        except Exception as e:
            print(f"Error reading file {file_path}: {e}")

daily_input_df = pd.concat(daily_input_data, ignore_index=True)

2025-07 valid daily files: 31
Skipping empty file: /content/drive/MyDrive/BSC_DPDM_Midterm2025/Input - (Operation Daily rain from API_ 2025)/2025-07/HII_daily_rainfall_2025-07-30.csv
2025-08 valid daily files: 31
2025-09 valid daily files: 30
2025-10 valid daily files: 31
2025-11 valid daily files: 30
2025-12 valid daily files: 31

In [14]:
daily_input_df['Source_Month'].value_counts().sort_index()

Source_Month
2025-07    26987
2025-08    27915
2025-09    27796
2025-10    29515
2025-11    31086
2025-12    32699
Name: count, dtype: int64

In [15]:
daily_input_df['date'] = pd.to_datetime(
    daily_input_df['rainfall_datetime_calc']
).dt.date

daily_input_df['date'].nunique()

183

In [16]:
import pandas as pd
daily_input_df = pd.concat(daily_input_data, ignore_index=True)

In [17]:
daily_input_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175998 entries, 0 to 175997
Data columns (total 8 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   rainfall_datetime       175998 non-null  object
 1   rainfall_datetime_calc  175998 non-null  object
 2   rainfall_value          175994 non-null  float64
 3   tele_station_id         172184 non-null  float64
 4   tele_station_oldcode    167148 non-null  object
 5   measure_datetime        175998 non-null  object
 6   Source_Month            175998 non-null  object
 7   Source_File             175998 non-null  object
dtypes: float64(2), object(6)
memory usage: 10.7+ MB

In [18]:
daily_input_df

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,Source_Month,Source_File
0,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.0,256.0,MKTR,2025-07-06,2025-07,HII_daily_rainfall_2025-07-06.csv
1,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.0,492350.0,ATG081,2025-07-06,2025-07,HII_daily_rainfall_2025-07-06.csv
2,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.0,806.0,TTLG,2025-07-06,2025-07,HII_daily_rainfall_2025-07-06.csv
3,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.8,745748.0,AIT005,2025-07-06,2025-07,HII_daily_rainfall_2025-07-06.csv
4,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.4,1109493.0,ONE004,2025-07-06,2025-07,HII_daily_rainfall_2025-07-06.csv
...,...,...,...,...,...,...,...,...
175993,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,572.0,CMSG,2025-12-03,2025-12,HII_daily_rainfall_2025-12-03.csv
175994,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,571.0,KKPA,2025-12-03,2025-12,HII_daily_rainfall_2025-12-03.csv
175995,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,569.0,NSRS,2025-12-03,2025-12,HII_daily_rainfall_2025-12-03.csv
175996,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,568.0,CPY001,2025-12-03,2025-12,HII_daily_rainfall_2025-12-03.csv
175997,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,567.0,PMPA,2025-12-03,2025-12,HII_daily_rainfall_2025-12-03.csv

## โฟลเดอร์ Daily rain

In [19]:
daily_rain_path = path + 'Daily rain - (Statistics 2012-2024)/'
os.listdir(daily_rain_path)

['hii_daily_rain.csv']

In [20]:
daily_rain_df = pd.read_csv('/content/drive/MyDrive/BSC_DPDM_Midterm2025/Daily rain - (Statistics 2012-2024)/hii_daily_rain.csv')
daily_rain_df

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ABRT,2012-01-01 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
1,ABRT,2012-01-03 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
2,ABRT,2012-01-06 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
3,ABRT,2012-01-07 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
4,ABRT,2012-01-08 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3768458,YOM016,2024-11-25 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily
3768459,YOM016,2024-11-26 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily
3768460,YOM016,2024-11-27 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily
3768461,YOM016,2024-11-28 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily
3768462,YOM016,2024-11-29 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily

In [66]:
daily_rain_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3768463 entries, 0 to 3768462
Data columns (total 15 columns):
 #   Column            Dtype
---  ------            -----
 0   station_code      object
 1   measure_datetime  object
 2   data              float64
 3   station_name      object
 4   latitude          float64
 5   longitude         float64
 6   quality_flag      object
 7   basin             object
 8   sub_basin         object
 9   tambon            object
 10  amphoe            object
 11  province          object
 12  data_type         object
 13  date              datetime64[ns, UTC+07:00]
 14  doy               int32
dtypes: datetime64[ns, UTC+07:00](1), float64(3), int32(1), object(10)
memory usage: 416.9+ MB

## โฟลเดอร์ Output

In [21]:
output_path = path + 'Output - (Clean monthly rain - 2025)/'
os.listdir(output_path)

['Y_monthly_rain_HII_operation.csv']

In [85]:
monthly_rain_df = pd.read_csv('/content/drive/MyDrive/BSC_DPDM_Midterm2025/Output - (Clean monthly rain - 2025)/Y_monthly_rain_HII_operation.csv')
monthly_rain_df

      Node   rain  month  year
0     ACRU   83.0      7  2025
1     ACRU  164.8      8  2025
2     ACRU  248.6      9  2025
3     ACRU   48.4     10  2025
4     ACRU   52.2     11  2025
5     ACRU    0.2     12  2025
6     BBHN  391.6      7  2025
7     BBHN  641.2      8  2025
8     BBHN  517.6      9  2025
9     BBHN  198.8     10  2025
10    BBHN  224.0     11  2025
11    BBHN    5.8     12  2025
12    BBUA  135.6      7  2025
13    BBUA   58.0      8  2025
14    BBUA   14.8      9  2025
15    BBUA   71.8     10  2025
16  YOM012  100.6     11  2025
17  YOM012    8.0     12  2025

In [86]:
monthly_rain_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Node    18 non-null     object
 1   rain    18 non-null     float64
 2   month   18 non-null     int64
 3   year    18 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 708.0+ bytes

## โครงสร้างข้อมูล

In [23]:
station_df.info()
station_df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385 entries, 0 to 384
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Node    385 non-null    object
 1   Lat     385 non-null    float64
 2   Long    385 non-null    float64
dtypes: float64(2), object(1)
memory usage: 9.2+ KB

(385, 3)

In [24]:
station_df.dtypes

Node     object
Lat     float64
Long    float64
dtype: object

In [25]:
station_df.isnull().sum()

Node    0
Lat     0
Long    0
dtype: int64

อธิบาย

In [26]:
daily_input_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175998 entries, 0 to 175997
Data columns (total 8 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   rainfall_datetime       175998 non-null  object
 1   rainfall_datetime_calc  175998 non-null  object
 2   rainfall_value          175994 non-null  float64
 3   tele_station_id         172184 non-null  float64
 4   tele_station_oldcode    167148 non-null  object
 5   measure_datetime        175998 non-null  object
 6   Source_Month            175998 non-null  object
 7   Source_File             175998 non-null  object
dtypes: float64(2), object(6)
memory usage: 10.7+ MB

In [27]:
daily_rain_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3768463 entries, 0 to 3768462
Data columns (total 13 columns):
 #   Column            Dtype
---  ------            -----
 0   station_code      object
 1   measure_datetime  object
 2   data              float64
 3   station_name      object
 4   latitude          float64
 5   longitude         float64
 6   quality_flag      object
 7   basin             object
 8   sub_basin         object
 9   tambon            object
 10  amphoe            object
 11  province          object
 12  data_type         object
dtypes: float64(3), object(10)
memory usage: 373.8+ MB

In [28]:
monthly_rain_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Node    18 non-null     object
 1   rain    18 non-null     float64
 2   month   18 non-null     int64
 3   year    18 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 708.0+ bytes

# **ข้อ2** กรองข้อมูลให้เหลือเฉพาะสถานีใน Stations in the model HII แสดงจำนวนก่อน/หลังกรอง

In [29]:
station_list = station_df['Node'].unique()

In [30]:
before_count = len(daily_input_df)
before_count

175998

In [31]:
filtered_df = daily_input_df[
    daily_input_df['tele_station_oldcode'].isin(station_list)
]
filtered_df

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,Source_Month,Source_File
0,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.0,256.0,MKTR,2025-07-06,2025-07,HII_daily_rainfall_2025-07-06.csv
2,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.0,806.0,TTLG,2025-07-06,2025-07,HII_daily_rainfall_2025-07-06.csv
5,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.0,602.0,NKYG,2025-07-06,2025-07,HII_daily_rainfall_2025-07-06.csv
7,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.0,477.0,NMPT,2025-07-06,2025-07,HII_daily_rainfall_2025-07-06.csv
11,2025-07-07 00:00:00+07:00,2025-07-07T07:00:00+07:00,0.0,443.0,LMPN,2025-07-06,2025-07,HII_daily_rainfall_2025-07-06.csv
...,...,...,...,...,...,...,...,...
175990,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,576.0,KOLO,2025-12-03,2025-12,HII_daily_rainfall_2025-12-03.csv
175991,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,575.0,BPPS,2025-12-03,2025-12,HII_daily_rainfall_2025-12-03.csv
175993,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,572.0,CMSG,2025-12-03,2025-12,HII_daily_rainfall_2025-12-03.csv
175994,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,571.0,KKPA,2025-12-03,2025-12,HII_daily_rainfall_2025-12-03.csv
175995,2025-12-04 00:00:00+07:00,2025-12-03T07:00:00+07:00,0.0,569.0,NSRS,2025-12-03,2025-12,HII_daily_rainfall_2025-12-03.csv

In [32]:
before_rows = daily_input_df.shape[0]
before_stations = daily_input_df['tele_station_oldcode'].nunique()

before_rows, before_stations

(175998, 1514)

In [33]:
station_list = station_df['Node'].unique()
station_list

array(['ACRU', 'BBHN', 'BBUA', 'BCNG', 'BDAR', 'BDCP', 'BDGN', 'BDLH',
       'BDMG', 'BGRT', 'BHMN', 'BHRA', 'BHUN', 'BJIG', 'BKDN', 'BKHL',
       'BKHN', 'BKK001', 'BKK008', 'BKK009', 'BKK015', 'BKK017', 'BKK018',
       'BKK019', 'BKUG', 'BKWN', 'BLAT', 'BLKO', 'BLUG', 'BMDG', 'BMNK',
       'BNAN', 'BNGR', 'BNHG', 'BNHI', 'BNHO', 'BNKN', 'BNKP', 'BNLG',
       'BNMK', 'BNPI', 'BNPU', 'BNTK', 'BOKA', 'BPIA', 'BPK004', 'BPLA',
       'BPPS', 'BPTG', 'BRKM', 'BSBA', 'BSDE', 'BSKJ', 'BSMP', 'BSPN',
       'BSUM', 'BTHO', 'BWKG', 'BYNU', 'CATK', 'CBUR', 'CCSS', 'CEHM',
       'CGDO', 'CGKM', 'CGMN', 'CGSN', 'CHHA', 'CHI005', 'CHI010',
       'CHI011', 'CHI012', 'CHI013', 'CHM001', 'CHM002', 'CHM003',
       'CHM004', 'CHN004', 'CHNA', 'CHPA', 'CHR003', 'CHR004', 'CHR005',
       'CHUN', 'CLPK', 'CMSG', 'CPKC', 'CPY003', 'CPY004', 'CPY009',
       'CPY010', 'CPY012', 'CPY013', 'CPY015', 'CPY017', 'CSMO', 'CTKN',
       'DCCT', 'DGSL', 'DITO', 'DIV001', 'DIV002', 'DIV003', 'DIV004',
       'DIV005', 'DKLG', 'DKTI', 'DMKH', 'DNCM', 'DSKT', 'DTAN', 'HCTT',
       'HKTG', 'HNKA', 'HNRE', 'HSYO', 'HTTM', 'HUYG', 'HYOD', 'HYRT',
       'JBLG', 'KABG', 'KAHN', 'KAKG', 'KANG', 'KAOP', 'KGKG', 'KGLN',
       'KHHM', 'KHPB', 'KKHA', 'KKPA', 'KKTO', 'KKWF', 'KMSI', 'KNYM',
       'KOKN', 'KOLO', 'KON002', 'KON004', 'KON005', 'KOSB', 'KOSK',
       'KOSR', 'KPEM', 'KRKM', 'KRN002', 'KSOD', 'KSPS', 'KTKB', 'KTLE',
       'KWSI', 'LBI002', 'LEEE', 'LK13', 'LMPN', 'LMSK', 'LNRG', 'LPLE',
       'MCHI', 'MCRM', 'MDTG', 'MECN', 'MEPK', 'MEWG', 'MKTR', 'MMMO',
       'MMNY', 'MNRM', 'MRMT', 'MUN011', 'MUN014', 'NAKU', 'NAMN',
       'NAN001', 'NAN006', 'NAN010', 'NAN011', 'NAN012', 'NAN013',
       'NAN014', 'NANI', 'NAPJ', 'NAPK', 'NASW', 'NBON', 'NEAK', 'NGBA',
       'NGCG', 'NGCH', 'NGNG', 'NGPI', 'NKMT', 'NKNN', 'NKO001', 'NKO002',
       'NKOK', 'NKSG', 'NKTI', 'NKYG', 'NMKH', 'NMKI', 'NMPR', 'NMPT',
       'NNKO', 'NNPT', 'NOKK', 'NPCT', 'NPI001', 'NPI002', 'NPNK', 'NPSD',
       'NSRS', 'NTAN', 'NTNG', 'NTST', 'NYK000', 'PAI002', 'PAII',
       'PAS001', 'PAS002', 'PAS008', 'PASG', 'PDAM', 'PGKH', 'PHON',
       'PHPS', 'PICI', 'PIN003', 'PIN004', 'PIN005', 'PIN006', 'PLTL',
       'PMPN', 'PONG', 'PPAN', 'PPCT', 'PPRM', 'PPTC', 'PRC002', 'PRC003',
       'PRGB', 'PRN001', 'PSLI', 'PSLT', 'PTLE', 'PTWY', 'PYMR', 'PYO001',
       'RAJ002', 'RAY001', 'RBPI', 'RGKG', 'RIKK', 'RNG001', 'RNGH',
       'SAY001', 'SAY002', 'SBT1', 'SENM', 'SGKW', 'SISU', 'SITP',
       'SKE001', 'SKE002', 'SKE003', 'SKG002', 'SKG005', 'SKG007', 'SKKG',
       'SKM004', 'SKM005', 'SLA002', 'SLBC', 'SMSU', 'SNGT', 'SNKO',
       'SOKL', 'SPPT', 'SPWA', 'SRKT', 'SSRG', 'STH004', 'STH005',
       'STH011', 'STH014', 'STH016', 'STH017', 'STH018', 'STH022',
       'STH025', 'STH029', 'STH030', 'STU001', 'STWN', 'SVI001', 'SVI002',
       'SWAR', 'SWH1', 'SWKL', 'SWNG', 'SYTL', 'TAPE', 'TEPT', 'TETN',
       'TGLG', 'TGSK', 'THA001', 'THA003', 'THA006', 'THA010', 'THA011',
       'THCG', 'THNG', 'THNM', 'THTN', 'TKFA', 'TKNT', 'TKRA', 'TLAN',
       'TLPC', 'TMLI', 'TNG001', 'TNG002', 'TOGO', 'TON001', 'TON006',
       'TPI001', 'TPI002', 'TPI004', 'TPI005', 'TPI007', 'TPPN', 'TPTN',
       'TPUR', 'TRD001', 'TRD002', 'TRON', 'TSLM', 'TSUD', 'TTKO', 'TTLG',
       'TTWY', 'TUKW', 'VLGE01', 'VLGE03', 'VLGE07', 'VLGE14', 'VLGE27',
       'VLGE29', 'VLGE31', 'VLGE32', 'VLGE33', 'VLGE41', 'VLGE42',
       'WAN001', 'WAN002', 'WAN005', 'WBYN', 'WCBR', 'WCHN', 'WCTK',
       'WEI071', 'WGCI', 'WGKN', 'WGNA', 'WGTG', 'WNKH', 'WNMI', 'WPAP',
       'WRRS', 'WSPN', 'WTBT', 'WTCH', 'WTLG', 'WTSG', 'WWST', 'YCUM',
       'YGHM', 'YOM001', 'YOM003', 'YOM008', 'YOM009', 'YOM010', 'YOM012'],
      dtype=object)

In [34]:
filtered_df = daily_input_df[
    daily_input_df['tele_station_oldcode'].isin(station_list)
]

In [35]:
after_rows = filtered_df.shape[0]
after_stations = filtered_df['tele_station_oldcode'].nunique()

after_rows, after_stations

(65913, 384)

In [36]:
import pandas as pd

summary = pd.DataFrame({
    'Stage': ['Before filtering', 'After filtering'],
    'Number of records': [before_rows, after_rows],
    'Number of stations': [before_stations, after_stations]
})

summary

              Stage  Number of records  Number of stations
0  Before filtering             175998                1514
1   After filtering              65913                 384

# **ข้อ3** ระบุข้อมูลสูญหาย (record ที่หายไป) ของแต่ละสถานี แสดงจำนวนและสัดส่วน

In [37]:
daily_input_df['date'] = pd.to_datetime(
    daily_input_df['rainfall_datetime_calc']
).dt.date

In [38]:
station_list = station_df['Node'].unique()
all_dates = daily_input_df['date'].unique()

In [39]:
expected = pd.MultiIndex.from_product(
    [station_list, all_dates],
    names=['tele_station_oldcode', 'date']
).to_frame(index=False)

In [40]:
observed = daily_input_df[['tele_station_oldcode', 'date']]

In [41]:
missing_daily = expected.merge(
    observed,
    on=['tele_station_oldcode', 'date'],
    how='left',
    indicator=True
)

missing_daily = missing_daily[missing_daily['_merge'] == 'left_only']

In [55]:
missing_by_station = (
    missing_daily
    .groupby('tele_station_oldcode')
    .size()
    .reset_index(name='Missing_records')
)

total_days = len(all_dates)
missing_by_station['Total_records'] = total_days
missing_by_station['Missing_ratio'] = (
    missing_by_station['Missing_records'] / total_days
)
missing_by_station['Missing_percent'] = missing_by_station['Missing_ratio'] * 100
missing_by_station.sort_values('Missing_percent', ascending=False)

,tele_station_oldcode,Missing_records,Total_records,Missing_ratio,Missing_percent
19,BKK009,183,183,1.000000,100.000000
209,NPI002,168,183,0.918033,91.803279
357,WAN005,148,183,0.808743,80.874317
69,CHI010,142,183,0.775956,77.595628
78,CHNA,137,183,0.748634,74.863388
...,...,...,...,...,...
355,WAN001,2,183,0.010929,1.092896
356,WAN002,2,183,0.010929,1.092896
362,WEI071,2,183,0.010929,1.092896
365,WGNA,2,183,0.010929,1.092896
384,YOM012,2,183,0.010929,1.092896

In [57]:
excluded_stations = missing_by_station[
    missing_by_station['Missing_percent'] >= 20
]

In [58]:
excluded_stations[['tele_station_oldcode', 'Missing_records', 'Missing_percent']]

    tele_station_oldcode  Missing_records  Missing_percent
16                  BKHN               89        48.633880
19                BKK009              183       100.000000
21                BKK017              130        71.038251
27                  BLKO               43        23.497268
32                  BNGR              120        65.573770
38                  BNLG               75        40.983607
48                  BPTG              132        72.131148
52                  BSKJ              109        59.562842
54                  BSPN               65        35.519126
62                  CEHM              101        55.191257
64                  CGKM               67        36.612022
69                CHI010              142        77.595628
72                CHI013              108        59.016393
78                  CHNA              137        74.863388
90                CPY010               42        22.950820
96                  CTKN               58        31.693989
97                  DCCT               83        45.355191
98                  DGSL               97        53.005464
132                 KKTO               39        21.311475
140               KON005               47        25.683060
156                 LMSK               42        22.950820
164                 MEWG              108        59.016393
166                 MMMO               41        22.404372
168                 MNRM               67        36.612022
183                 NAPK              114        62.295082
184                 NASW              106        57.923497
186                 NEAK               58        31.693989
188                 NGCG               40        21.857923
191                 NGPI               56        30.601093
197                 NKSG               48        26.229508
205                 NNPT              102        55.737705
209               NPI002              168        91.803279
221               PAS008              126        68.852459
233                 PMPN               67        36.612022
242               PRN001              127        69.398907
244                 PSLT              130        71.038251
260                 SGKW               50        27.322404
263               SKE001               47        25.683060
270               SKM004               62        33.879781
272               SLA002               39        21.311475
331               TPI007               46        25.136612
343                 TUKW              122        66.666667
350               VLGE31               38        20.765027
352               VLGE33               48        26.229508
357               WAN005              148        80.874317
377                 YCUM              127        69.398907
379               YOM001               86        46.994536

In [59]:
num_excluded = excluded_stations['tele_station_oldcode'].nunique()
num_excluded

47

In [60]:
remaining_stations = missing_by_station[
    missing_by_station['Missing_percent'] < 20
]

In [61]:
num_remaining = remaining_stations['tele_station_oldcode'].nunique()
num_remaining

338

In [62]:
summary_q4 = pd.DataFrame({
    'Category': ['Excluded stations (missing ≥ 20%)', 'Remaining stations'],
    'Number of stations': [num_excluded, num_remaining]
})

summary_q4

                            Category  Number of stations
0  Excluded stations (missing ≥ 20%)                  47
1                 Remaining stations                 338

# **ข้อ5** เติมข้อมูลที่หายไปด้วยค่า Median ตาม Day of Year จาก historical แยกตามสถานี ตรวจสอบว่าไม่มี record หายอีก

In [67]:
median_doy_station = (
    daily_rain_df
    .groupby(['station_code', 'doy'])['data']
    .median()
    .reset_index()
    .rename(columns={
        'station_code': 'tele_station_oldcode',
        'data': 'median_rainfall'
    })
)

In [68]:
daily_input_df['date'] = pd.to_datetime(daily_input_df['measure_datetime'])
daily_input_df['doy'] = daily_input_df['date'].dt.dayofyear

In [69]:
stations = remaining_stations['tele_station_oldcode'].unique()
all_dates = pd.date_range(
    daily_input_df['date'].min(),
    daily_input_df['date'].max(),
    freq='D'
)

full_index = pd.MultiIndex.from_product(
    [stations, all_dates],
    names=['tele_station_oldcode', 'date']
)

full_df = full_index.to_frame(index=False)
full_df['doy'] = full_df['date'].dt.dayofyear

In [70]:
daily_complete = full_df.merge(
    daily_input_df,
    on=['tele_station_oldcode', 'date', 'doy'],
    how='left'
)

In [71]:
daily_complete = daily_complete.merge(
    median_doy_station,
    on=['tele_station_oldcode', 'doy'],
    how='left'
)

daily_complete['rainfall_filled'] = daily_complete['rainfall_value']
daily_complete.loc[
    daily_complete['rainfall_filled'].isna(),
    'rainfall_filled'
] = daily_complete['median_rainfall']

In [72]:
daily_complete['rainfall_filled'].isna().sum()

np.int64(0)

In [73]:
pd.DataFrame({
    'Stage': ['Before filling', 'After filling'],
    'Missing records': [
        daily_complete['rainfall_value'].isna().sum(),
        daily_complete['rainfall_filled'].isna().sum()
    ]
})

            Stage  Missing records
0  Before filling              842
1   After filling                0

# **ข้อ6** เหตุใดใช้ Median แทน Mean?

เนื่องจากข้อมูลปริมาณน้ำฝนมีการกระจายแบบเบ้และมักมีค่าผิดปกติจากเหตุการณ์ฝนตกหนัก การใช้ค่าเฉลี่ย (Mean) อาจทำให้ค่าที่นำมาเติมสูงเกินความเป็นจริงและบิดเบือนลักษณะปกติของข้อมูล ดังนั้นจึงเลือกใช้ค่ามัธยฐาน (Median) ซึ่งมีความทนทานต่อค่าผิดปกติและสะท้อนค่ากลางที่เหมาะสมของปริมาณน้ำฝนในแต่ละวันได้ดีกว่า โดยเฉพาะเมื่อพิจารณาแยกตามสถานีและวันในรอบปี (Day of Year) เพื่อคงลักษณะเชิงฤดูกาลของข้อมูลไว้ในการวิเคราะห์

# **ข้อ7** คำนวณผลรวมปริมาณน้ำฝนรายเดือน จัดรูปแบบให้ตรงกับ output_monthly_rainfall.csv

In [100]:
daily_complete['year'] = daily_complete['date'].dt.year
daily_complete['month'] = daily_complete['date'].dt.month

In [101]:
monthly_rain_df2 = (
    daily_complete
    .groupby(['tele_station_oldcode', 'year', 'month'])['rainfall_filled']
    .sum()
    .reset_index()
)

In [102]:
monthly_rain_df = monthly_rain_df.rename(columns={
    'tele_station_oldcode': 'Node',
    'rainfall_filled': 'rain'
})

In [103]:
monthly_rain_df = monthly_rain_df.sort_values(
    ['year', 'month', 'Node']
).reset_index(drop=True)

In [104]:
monthly_rain_df.info()
monthly_rain_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2028 entries, 0 to 2027
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Node    2028 non-null   object
 1   year    2028 non-null   int32
 2   month   2028 non-null   int32
 3   rain    2028 non-null   float64
dtypes: float64(1), int32(2), object(1)
memory usage: 47.7+ KB

   Node  year  month   rain
0  ACRU  2025      7   96.9
1  BBHN  2025      7  375.0
2  BBUA  2025      7  145.0
3  BCNG  2025      7  254.2
4  BDAR  2025      7   37.2

In [84]:
monthly_rain_df

        Node  year  month   rain
0       ACRU  2025      7   96.9
1       BBHN  2025      7  375.0
2       BBUA  2025      7  145.0
3       BCNG  2025      7  254.2
4       BDAR  2025      7   37.2
...      ...   ...    ...    ...
2023  YOM003  2025     12    5.0
2024  YOM008  2025     12    7.0
2025  YOM009  2025     12    4.2
2026  YOM010  2025     12    1.6
2027  YOM012  2025     12    8.0

[2028 rows x 4 columns]

In [ ]:
monthly_rain_df.to_csv(
    'output_monthly_rainfall.csv',
    index=False
)

In [88]:
daily_complete['year'] = daily_complete['date'].dt.year
daily_complete['month'] = daily_complete['date'].dt.month
   # มีคอลัมน์: station_id, obs_date, rain_filled

In [89]:
monthly_rain_df = (
    daily_complete
    .groupby(['tele_station_oldcode', 'year', 'month'])['rainfall_filled']
    .sum()
    .reset_index()
)

In [90]:
monthly_rain_df = monthly_rain_df.rename(columns={
    'tele_station_oldcode': 'Node',
    'rainfall_filled': 'rain'
})

In [91]:
monthly_rain_df = monthly_rain_df.sort_values(
    ['year', 'month', 'Node']
).reset_index(drop=True)

In [92]:
monthly_rain_df.info()
monthly_rain_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2028 entries, 0 to 2027
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Node    2028 non-null   object
 1   year    2028 non-null   int32
 2   month   2028 non-null   int32
 3   rain    2028 non-null   float64
dtypes: float64(1), int32(2), object(1)
memory usage: 47.7+ KB

   Node  year  month   rain
0  ACRU  2025      7   96.9
1  BBHN  2025      7  375.0
2  BBUA  2025      7  145.0
3  BCNG  2025      7  254.2
4  BDAR  2025      7   37.2

In [111]:
monthly_rain_df

        Node  year  month   rain
0       ACRU  2025      7   96.9
1       BBHN  2025      7  375.0
2       BBUA  2025      7  145.0
3       BCNG  2025      7  254.2
4       BDAR  2025      7   37.2
...      ...   ...    ...    ...
2023  YOM003  2025     12    5.0
2024  YOM008  2025     12    7.0
2025  YOM009  2025     12    4.2
2026  YOM010  2025     12    1.6
2027  YOM012  2025     12    8.0

[2028 rows x 4 columns]

In [114]:
# กำหนด path โฟลเดอร์ (ใช้ path เดิมที่กำหนดไว้สำหรับ Google Drive)
import os
output_path = path + 'Output - (Clean monthly rain - 2025)'

# สร้างโฟลเดอร์ถ้ายังไม่มี
os.makedirs(output_path, exist_ok=True)

# บันทึกไฟล์ CSV
monthly_rain_df.to_csv(
    f"{output_path}/output_monthly_rainfall_2025.csv",
    index=False
)